#!/bin/bash

iptables -P INPUT DROP

# Red 10.2.0.0/29 ACCESO 1
iptables -A INPUT -s 10.2.0.0/29 -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -s 10.2.0.0/29 -p udp --dport 5060 -j ACCEPT
iptables -A INPUT -s 10.2.0.0/29 -p udp --dport 16384:16482 -j ACCEPT
# AQUI PERMITIMOS COMUNICARSE LOS ASTERISK KEEPALIVED (DISPONIBILIDAD)
iptables -A INPUT -s 10.2.0.6 -p vrrp -j ACCEPT

# Red 10.3.0.0/29 ACCESO 2
iptables -A INPUT -s 10.3.0.0/29 -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -s 10.3.0.0/29 -p udp --dport 5060 -j ACCEPT
iptables -A INPUT -s 10.3.0.0/29 -p udp --dport 16384:16482 -j ACCEPT

